### ISSUE TITLE
Splitting marty into multiple packages

### ISSUE THREAD

**Issue by dariocravero** [martyjs/marty#186]
Hi all,

I've been working in and with [Padrino](https://github.com/padrino/padrino-framework) for a long while now and one of the things that always attracted more and more people to it was the fact that you could very easily mix and match components at will.

In other words, it was the framework being agnostic and split into logical blocks that anybody could reuse what made people want to use it in their applications.

I was just reviewing the dependencies in a new package and realised that `marty` was requiring `react` as a dependency but I didn't really needed it at all, the project is only dealing with `stores`, `constants` and `action creators`. So it hit me, what about splitting `marty` into a set of logical (and potentially interchangeable) packages up to where it makes sense?

From looking at the current state of the project, I'd suggest something along the lines of:
- `marty-action-creators`,
- `marty-component`,
- `marty-constants`,
- `marty-core`,
- `marty-state-source` and
- `marty-store`.

A package named `marty` could still be grouping all of these into a common namespace as it is doing so now.

Going further, this could potentially allow for the project to move to its own organisation in GitHub which would make more people involved over time as it would feel more community focused that way.

What do you think about that?
Thanks,
Darío

**Comment by jhollingworth** [comment]
I'm all for splitting everything out. Let me have a think about it and its something we can do in v0.10

**Comment by dariocravero** [comment]
Brilliant!
