### ISSUE TITLE
Normalise displayName and id usage across registerables

### ISSUE THREAD

**Issue by dariocravero** [martyjs/marty#223]
This issue is to open a discussion on normalising `displayName` and `id` usage across types that are meant to be registered in Marty, [`displayName` would preferably replace `id`](https://gitter.im/jhollingworth/marty?at=5512c5d9c25916c13d34fa24).

- [ ] Normalise registerables
  - [ ] `ActionCreator`
  - [ ] `Store`
  - [ ] `StateSource`
- [ ] Clarify the usage of `__id` in the code

**Comment by jhollingworth** [comment]
This problem should go away in v0.10. Going to close for now
