### ISSUE TITLE
Support react-native

### ISSUE THREAD

**Issue by jhollingworth** [martyjs/marty#230]
https://github.com/facebook/react-native

**Comment by dariocravero** [comment]
:+1: I wonder what's really needed for it?

**Comment by davidpadbury** [comment]
I've been attempting to do a native version of marry-chat-example app as an excuse to playing with react-native. The biggest challenge appears to be react-native's packaging of marty.

React-native has it's own packager which doesn't behave like browserify. As a result requiring marty hits a bunch of problems with node core modules not being available (so far events and url). I think my next problem will be the packager not taking browserify packages for libs like isomorphic-fetch.

Will let you know if I get any further.

**Comment by jhollingworth** [comment]
We could happily replace Events with [Wolfy87/EventEmitter](https://github.com/Wolfy87/EventEmitter) however isomorphic-fetch is going to be a bit trickier. Thanks to [fetch](http://facebook.github.io/react-native/docs/network.html#fetch) being natively supported we don't need that dependency at all however I don't think there's anyway to have optional dependencies based on environment. I think the solution is going to be to create `marty-native` which only has the dependencies we need for native. This would also allow us to have a separate entry point for native.

All this might support the case for #186

**Comment by dariocravero** [comment]
Yup, different will definitely help here :)

**Comment by jhollingworth** [comment]
It seems you get it working with [webpack](https://github.com/roman01la/react-native-babel)

**Comment by davidpadbury** [comment]
I haven't yet looked at quite what the react-native packager does in detail. If we were able to use browserify to create the index.ios.js bundle a lot of these problems would go away.

A `marty-native` is probably the right way to go.

**Comment by jhollingworth** [comment]
I've finally got [native support](https://github.com/jhollingworth/marty-native-scratch) (alpha). Its required me to explode marty into separate modules so we have finer [grained control over what modules we install](https://github.com/martyjs/marty-native/blob/master/marty.js). On the upside marty is now massively modular and you can easily add/remove things as you wish!

I'm going to polish this over the next few days
