### ISSUE TITLE
Containers needs a no-op callback

### ISSUE THREAD

**Issue by sporto** [martyjs/marty#242]
Take a use case where in `fetch` you get a value from somewhere else, e.g. a keyword from props. This keyword could be an empty string, in this case I wouldn't want to make a request, I will like to just render a message:

```js
export default Marty.createContainer(List, {
  listenTo: librariesStore,
  fetch: {
     libraries() {
        var keyword = this.props.keyword;
        if (keyword === '') return null; //somehow signal that we don't want to do anything
			return librariesStore.for(this).fetchLibraries(keyword);
		}
	},
  failed(errors) {
      return <div className="User User-failedToLoad">ERRORS {errors}</div>;
  },
  pending() {
    return <Loader />;
  },
  noOp() {
       return <div>Please type a keyword</div>
  }
})
```

I can render this message in the component passing the keyword prop, but it would be nice to be able to do it here. Anything like this possible already?

**Comment by jhollingworth** [comment]
Could you just override `done`?

**Comment by sporto** [comment]
You mean something like?

```
export default Marty.createContainer(List, {
	listenTo: librariesStore,
	fetch: {
		libraries() {
			var keyword = this.props.keyword;
			if (keyword === '') return null;
        		return librariesStore.for(this).fetchLibraries(keyword);
		}
	},
	failed(errors) {
		return <div className="User User-failedToLoad">ERRORS {errors}</div>;
	},
	pending() {
		return <Loader />;
	},
	done(results) {
  		if (results) {
   			return <InnerComponent ref="innerComponent" {...this.props} {...results} />;
   		} else {
			return <div>Please type a keyword</div>
		}
	}
})
```

I haven't tried yet, but I wonder if this use case is not generic enough to warrant its own callback (maybe not if I am the only one asking).

**Comment by jhollingworth** [comment]
Hey, I haven't seen enough cases where this would be useful to warrant its own callback. Going to close for now but please re-open if you've got anything to add
