### ISSUE TITLE
Update examples to use fetch behavior, containers, etc

### ISSUE THREAD

**Issue by geoffharcourt** [martyjs/marty#246]
The 0.9.x features are great, but I think it's a bit difficult to tell from the docs exactly how one should be implementing a container that uses remote data. I went down a wrong path for a bit when deciding between using the container's `#fetch`, `#pending`, and `#fail` methods vs. using `#when` inside `#fetch`. The examples are updated for 0.9.x, but they don't leverage the new functionality. Given all the great changes, I think a revamped example would be extremely useful to new users given the expansion of API concepts present in 0.9.

Also, really excited about the progress.

**Comment by jhollingworth** [comment]
Yeah, good point. I will expand the [fetching state](http://martyjs.org/guides/fetching-state/index.html) article

**Comment by taion** [comment]
It'd also be worth saying something about why `locally` and `remotely` don't explicitly have to be bound to the `Store` in that documentation.

**Comment by idolize** [comment]
@geoffharcourt Can you elaborate more on the wrong path you started on and where you landed? Thanks.

**Comment by geoffharcourt** [comment]
@idolize, I got confused about where I should be implementing the `when()` function to resolve results of my remote fetches. I currently have containers implementing them (with the appropriate `done()`, `pending()`, and `failed()` functions returning HTML), but on my first pass through it seemed like that was something I would be implementing either in my store or that I would have those methods return objects rather than HTML and let the `render()` function handle the output.

This could just be me misreading the docs, but I think seeing some kind of best practice example in the chat or todo app would be helpful for Flux/Marty converts who are still learning the implementation gotchas.

**Comment by jhollingworth** [comment]
I've updated the v0.10 docs with some more examples http://martyjs.org/v/0.10.0-beta/guides/fetching-state/index.html. This should be released sometime this week
