### ISSUE TITLE
Idea: time to live for fetched data in stores

### ISSUE THREAD

**Issue by geoffharcourt** [martyjs/marty#255]
As it stands, once you fetch data for a store, the `locally` method will continue to serve it up on future access. If you want to invalidate it, (I think) the best approach is to either repopulate the data using a Query or to reset the store's state properties to `undefined`. 

What if there was a `timeToLive` that you specified as a property on fetch? Users would specify a number of seconds for which store data would be essentially cached. Invocations of `fetch` after the TTL expired would trigger the `remotely` function, but in the event `remotely` failed, the store's state would be unaltered, and `locally` would execute as it does now.

**Comment by oliverwoodings** [comment]
I don't think Marty should be responsible for doing this. Invalidation is a very broad concept; different applications often have very different requirements for invalidating data.

**Comment by sporto** [comment]
I agree that marty shouldn't do this, you can do this in `locally` with whatever logic you want.

**Comment by jhollingworth** [comment]
I'm in agreement this is probably not something that should be in marty. Gonna close this for now but feel free to re-open if you have more evidence for why we should have it
