### ISSUE TITLE
Should Store.handlers be static?

### ISSUE THREAD

**Issue by taion** [martyjs/marty#262]
When using the ES6 syntax, instead of:

```js
class UsersStore extends Marty.Store {
  constructor(options) {
    super(options);
    this.state = {};
    this.handlers = {
      addUser: Constants.RECEIVE_USER
    };
  }
  addUser(user) {
    this.state[user.id] = user;
    this.hasChanged();
  }
}
```

I think it would make more sense to have

```js
class UsersStore extends Marty.Store {
  constructor(options) {
    super(options);
    this.state = {};
  }
  addUser(user) {
    this.state[user.id] = user;
    this.hasChanged();
  }
}
UsersStore.handlers = {
  addUser: Constants.RECEIVE_USER
};
```

This is more consistent with how class-level things like `defaultProps`, `propTypes`, and `contextTypes` work in React. I can't think of a good reason to make the handler map be per-instance instead of per-class.

**Comment by sporto** [comment]
I wonder if there is ever a use case when you want to modify the handlers depending on the options. I don't think I would do this, but worth considering if this is something someone could want.

```js
class UserStore extends Marty.Store {
 constructor(options) {
    super(options);
    this.state = {};
    this.handlers = {
      addUser: Constants.RECEIVE_USER
    };
   if (options.something) {
     this.handlers.deleteUser: Constants.DELETE_USER
   } else {
    this.handlers.deleteUserAlt: Constants.DELETE_USER
   }
  }
}
```

**Comment by jhollingworth** [comment]
What about if the handlers are passed through the options, giving you the option to modify them in the constructor before passing it to the parent?

```js
class UserStore extends Marty.Store {
  constructor(options) {
    this.state = {};

    if (options.something) {
      options.handlers.deleteUser = Constants.DELETE_USER
    } else {
      options.handlers.deleteUserAlt = Constants.DELETE_USER
    }

    super(options);
  }
}

UserStore.handlers = {
  addUser: Constants.RECEIVE_USER
};
```

**Comment by jhollingworth** [comment]
Fortunately this all goes away with [ES7 class Properties](https://gist.github.com/jeffmo/054df782c05639da2adb)

```js
class UserStore extends Marty.Store {
  handlers = {
    addUser: Constants.RECEIVE_USER
  }
}
```

**Comment by taion** [comment]
I feel like using `options` to modify handlers is a little bit odd. I think in those cases I'd probably rather just extend the the store (e.g. `UserStoreAlt extends UserStore`), or take the branch inside the handler itself.

IMO the "final form" of the syntax if you will ought to look something like

```js
class UserStore extends Marty.Store {
  @Marty.Handles(UserConstants.RECEIVE_USER)
  addUser(user) {
    ...
  }
}
```

And something like that would very much require the handlers to be static and immutable.

**Comment by jhollingworth** [comment]
Yeah, decorators are much nicer! [Babel has experimental support for them](https://babeljs.io/docs/usage/experimental/), it would be interesting to add this for v0.10

**Comment by taion** [comment]
Okay, so I take back what I said earlier, then. Implementation-wise the decorator-based approach is just going to look like

```
class UserStore extends Marty.Store {
  addUser(user) {
    ...
  }
}
UserStore.prototype.addUser.handles = UserConstants.RECEIVE_USER;
```

in terms of what it ends up doing. I actually like this syntax more than the existing one anyway, and there's no need to have more ways of defining handlers than strictly necessary (i.e. don't add the class static handler map when we already have the per-instance one).

This can be done in a backward-compatible way. What do you think of how it looks?

**Comment by jhollingworth** [comment]
Would you advocate using this approach manually or just through decorators?

Makes sense for decorators but It seems a little verbose for manually defining action handlers with this way
```js
UserStore.prototype.addUser.handles = UserConstants.RECEIVE_USER;
UserStore.prototype.updateUser.handles = UserConstants.UPDATE_USER;
UserStore.prototype.removeUser.handles = UserConstants.REMOVE_USER;
```

**Comment by taion** [comment]
On second thought, probably not. I personally would probably prefer to do it this way if I didn't have the option of using babel, because I like the idea of getting a `TypeError` immediately if I typo a method name, and it feels a bit more explicit. However, when you write it out that way, though, it does look a bit uncomfortably verbose to be worth advocating over the existing implementation.

**Comment by sporto** [comment]
As I understand from the ES7 class properties link above something like:

```
class UserStore extends Marty.Store {
  handlers = {
    addUser: Constants.RECEIVE_USER
  }
}
``

Would be exactly the same as:
```
class UserStore extends Marty.Store {
	constructor () {
		this.handlers = {
			addUser: Constants.RECEIVE_USER
	  	}
	}
}
```

So class properties just go to the instance.

In the decorator example:

```
class UserStore extends Marty.Store {
  @Marty.Handles(UserConstants.RECEIVE_USER)
  addUser(user) {
    ...
  }
}
```

Where do you define 'addUser'? Does the decorator work on the method next to its declaration?

Finally In

```
UserStore.prototype.addUser.handles = UserConstants.RECEIVE_USER;
UserStore.prototype.updateUser.handles = UserConstants.UPDATE_USER;
UserStore.prototype.removeUser.handles = UserConstants.REMOVE_USER;
```


why `addUser.handles`? and not `handles.addUser`?

You could just do:

```
UserStore.prototype.handles = {
		addUser: UserConstants.RECEIVE_USER,
		...
	}
```


But I believe that putting objects in the prototype is a bad idea, this can lead to subtle bugs for people that don't quite understand the JS object model. e.g. the modify the object in one instance, thinking that that only affect that said instance, but it affects all existing and future instances.

**Comment by taion** [comment]
Per the decorator spec: https://github.com/wycats/javascript-decorators

We have

```js
class UserStore extends Marty.Store {
  @Marty.Handles(UserConstants.RECEIVE_USER)
  addUser(user) {
    ...
  }
}
```

being the roughly same as (with ES7 initializers)

```js
class UserStore extends Marty.Store {
  addUser(user) {
    ...
  }
}

UserStore.prototype.addUser = Marty.Handles(UserConstants.RECEIVE_USER)(UserStore.prototype.addUser) || UserStore.prototype.addUser;
```

except it would work on the descriptor rather than on the method itself. You would write the decorator as:

```js
function handles(actions) {
  return function (descriptor) {
    descriptor.value.handles = actions;
    // Optionally return the descriptor here, depending on preference.
  }
}
```

which means that what you end up with would be

```js
class UserStore extends Marty.Store {
  addUser(user) {
    ...
  }
}

UserStore.prototype.addUser.handles = UserConstants.RECEIVE_USER);
```

**Comment by jhollingworth** [comment]
An alternative I've floated a while ago was to remove handlers altogether

```js
class UserStore extends Marty.Store {
  getUser(id) {
    return this.state[id];
  }

  handleAction(action) {
    let { user } = action.payload

    switch (action.type) {
      case UserConstants.ADD_USER:
        this.state[user.id] = user
        this.hasChanged()
        break
      case UserConstants.REMOVE_USER:
        delete this.state[user.id]
        this.hasChanged()
    }
  }
}
```

**Comment by taion** [comment]
I feel like that's a lot more flexible than it needs to be. In most cases you just want to map actions to handlers, so having that `handlers` map (albeit specified the other way around) just seems like an easier way for the user to specify what he wants. I think I'd prefer to use separate handlers and define a map.

**Comment by sporto** [comment]
The way I understood the decorators proposal is that the `Class.prototype` is passed to the decorator as first argument. So:

```js
class UserStore {
  @Marty.Handles(UserConstants.RECEIVE_USER)
  addUser(user) {
	  ...
  }
}

function Handles(action) {
	return function (target, key, descriptor) {
		target.handlers = target.handlers || {}
		target.handlers[key] = action;
		return descriptor;
	}
}
```

Will resolve to 

```js
UserStore.prototype.handlers = {
	addUser: UserConstants.RECEIVE_USER,
		...
	}
```

**Comment by sporto** [comment]
re switch statement. I think having a map is simpler an easier to read. Current approach is fine.

**Comment by jhollingworth** [comment]
These 3 syntaxes will be supported in v0.10

```js
let { handles } = require('marty');

class UserStore extends Marty.Store {
  static handlers = {
    receiveUser: ["RECEIVE_USER", "CREATE_USER"]
  }

  @handles("RECIEVE_USER", "CREATE_USER")
  recieveUser(user) {
    ...
  }
}

UserStore.handlers = {
  receiveUser: ["RECEIVE_USER", "CREATE_USER"]
};
```
