### ISSUE TITLE
Can a store listen to another store ?

### ISSUE THREAD

**Issue by quazzie** [martyjs/marty#280]
Can i make a store that listens to other stores ?
Say if i wanted to make an aggregated store.

**Comment by jhollingworth** [comment]
Hey, you can't from a container but fetches can have dependencies (using dependsOn)

**Comment by quazzie** [comment]
Not a container, from a store.
```
class AggStore extends Marty.Store {
  listenTo: [StoreOne, StoreTwo],
  getInitialState() { this.state = { result: { one: null, two: null } }; }
  onStoreOneChange() { 
    this.state.result.one = OneStore.for(this).state.one;
    this.hasChanged();
  }
  onStoreTwoChange() { 
    this.state.result.two = OneStore.for(this).state.two;
    this.hasChanged();
  }
}
```

**Comment by jhollingworth** [comment]
Sorry, completely mis-read the question!

Right now stores don't listen to one another directly but that could be interesting. What use cases do you need this for?

Also, its worth noting if a fetch depends on another fetch that is pending then the store will automatically update when then the dependent fetch is done/failed

**Comment by quazzie** [comment]
I would like a store that aggregates data from other stores.

If the aggregate store returns a new object every time i ask for something i can't use PureRenderMixin. 
If i can update my aggregated data when the depending stores change PureRenderMixin will work.

quick example: 
```
class LogStore extends Marty.Store {
  constructor() {
    this.state = { logs: {} };
    this.handlers = { addLogs: Logconsts.GOT_LOGS }
  }
  addLogs(logs) {
    logs.forEach(log => this.state.logs[log.ID] = log);
    this.hasChanged();
  }
}

class DataStore extens Marty.Store {
  constructor() {
    this.state = { data: {} };
    this.handlers = { addData: Dataconsts.GOT_DATA };
  }

  addData(data) {
    this.state.data[data.id] = data;
    this.hasChanged();
  }
}

class PageStore extends Marty.Store {
  constructor() {
    this.state = { results: [] };
    this.listenTo = [LogStore, DataStore];
    this.handlers = { gotSearch: Pageconsts.GOT_SEARCH };
  }

  gotSearch(ids) {
    this.state.results = ids.map(id => ({ 
      id: id,
      log: LogStore.state.logs[id], 
      data: DataStore.state.data[id] 
    });
    this.hasChanged();
  }

  onLogStoreChanged() {
    this.state.results.forEach(item => item.log = LogStore.state.logs[item.id]);
    this.hasChanged();
  }
  onDataStoreChanged() {
    this.state.results.forEach(item => item.data = DataStore.state.data[item.id]);
    this.hasChanged();
  }
}
```

**Comment by oliverwoodings** [comment]
:+1: just came across a scenario where this would be useful for me too (i have an aggregate store that combines data from my router store and other data stores).

**Comment by jhollingworth** [comment]
hey, sorry for late reply. So I get the value and would be happy to introduce it. We already have `StoreObserver` internally which does this for you:

```js
let observer = new StoreObserver({
   stores: [FooStore, BarStore],
   onStoreChanged: () => console.log('store changed')
});
```

My problem is I'm not 100% what the syntax should look like. It would make sense for `listenTo` to be an object hash which would behave similarly to `handlers`.   

```js
this.listenTo = {
  onLogStoreChanged: LogStore,
  onDataStoreChanged: DataStore
};    
```

I have 2 concerns with this though
1. It doesn't conform to the existing `listenTo` syntax, i.e. an array.
2. Its very similar to `handlers` and I can foresee confusion there

I had thought about allowing you to specify stores alongside constants in `handlers` which makes a lot of sense.

```js
this.handlers = {
  onLogStoreChanged: LogStore,
  onDataStoreChanged: DataStore,
  gotSearch: PageConstants.GOT_SEARCH
};
```
However in v0.10 you will be able to reference stores by a string Id and so there will be an ambiguity between string constants store's. Not certain how to solve that...

Another approach would be, like `listenTo` at the moment, only have a single callback known callback that is invoked when any store you are listening to changes.

```js
class PageStore extends Marty.Store {
  constructor() {
    this.state = { results: [] };
    this.listenTo = [LogStore, DataStore];
    this.handlers = { gotSearch: PageConstants.GOT_SEARCH };
  }

  onStoreChanged() {
    ...
  }
}
```

The problem there is how to specify what function is called. I don't like the idea of having a reserved function that gets called so we need a way of specifying the function to call. A solution here would be to make `listenTo` a function which accepts an array and a callback.

```js
class PageStore extends Marty.Store {
  constructor() {
    this.listenTo([LogStore, DataStore], this.onStoreChanged);
  }

  onStoreChanged() {
    ...
  }
}
```

However this doesn't really fit in with how `handlers` are defined and will look more out of place when we move to assigning static variables

```js
class PageStore extends Marty.Store {
  static handlers = {
    gotSearch: PageConstants.GOT_SEARCH
  }

  constructor() {
    this.listenTo([LogStore, DataStore], this.onStoreChanged);
  }

  onStoreChanged() {
    ...
  }

  gotSearch() {
    ...
  }
}
```

Not sure what the best solution is right now, its got me a bit stumped

**Comment by oliverwoodings** [comment]
What about using the word 'observe' instead for the object hash? I think it
is different enough from 'handlers' for people to not get confused.

**Comment by songawee** [comment]
Some ways we have been going about this issue are to either just have a container to listenTo many stores, or to utilize the waitFor syntax. It depends on your use case. If you just need data from different sources, I would use a container. If you need to build up objects that have pieces of data from other stores, I would have those stores listen to the same action as they are mutated and utilize the waitFor syntax to be able to pull in the data from the other stores at the right time.
