### ISSUE TITLE
Cookie state source fails with user.id: key.replace is not a function

### ISSUE THREAD

**Issue by imjared** [martyjs/marty#282]
![image](https://cloud.githubusercontent.com/assets/525011/7257175/a68abe16-e821-11e4-95f7-a6f958608322.png)

Relevant code:
```
var AuthCookie = Marty.createStateSource({

    id: 'AuthCookie',
    type: 'cookie',

    login: function( user ) {
        this.set( user.id, true );
        AuthSourceActions.loginSuccess( user );
    },
...
```

This might be a bit nitpicky so feel free to close if you disagree. The [example in the docs](http://martyjs.org/api/state-sources/cookie.html) passes `user.id` but a cookie key should be a string https://github.com/ScottHamper/Cookies/blob/master/src/cookies.js#L86.

Might be worth clarifying that?

**Comment by jhollingworth** [comment]
Sorry for delay getting back to you. I've [added an invariant](https://github.com/martyjs/marty-lib/commit/0a60c8aefe0ced6560b94f8883d7e31ee39d70e3) to ensure the key is always a string
