### ISSUE TITLE
Discrepancy between containers doc and fetching store

### ISSUE THREAD

**Issue by ariddell** [martyjs/marty#283]
Not sure if this is a typo. In Containers you have
```
return UserStore.for(this).getUser(this.props.id);
```

and in fetching-state you have (in the same situation)

```
return UserStore.getUser(this.props.userId);
```

I'm unclear what ``.for(this)`` does.

**Comment by hansihe** [comment]
As I have understood it, `UserStore.for(this).getUser(this.props.id)` makes sure the `getUser` method is being run on an instance of `UserStore` that has been registered on the same context as `this`.

Omitting `.for(this)` would work just fine in the browser where there is only one Marty context. Issues start to arise when multiple instances of the application get run in the same process, as is the case when writing isomorphic apps (application initially runs on the server, the state is then serialized and sent to the client with the initial http request).

The need for `.for(this)` is explained in further detail [here](http://martyjs.org/guides/isomorphism/index.html). Maybe it would be beneficial to include links to this, or a small expaination in the places where it is being used?

**Comment by ariddell** [comment]
Thanks. I didn't see the isomorphism bit.

**Comment by jhollingworth** [comment]
Going to close this now. Please re-open if you've got anything to add
