### ISSUE TITLE
Is the Fetch library a hard dependency?

### ISSUE THREAD

**Issue by dkingman** [martyjs/marty#286]
It says in the docs that we can swap out HTTP State Source `request()` implementations, as long as it returns a Promise. But in the `Store` it looks like [we are counting on what `Fetch` returns](https://github.com/martyjs/marty/blob/0fd8abec7440112a09f467a9a5417c15e9a7ead8/lib/store/fetch.js#L86-L109). Namely, `then` and `catch`.  So is [Fetch](https://github.com/github/fetch/) a hard dependency or not?

**Comment by FoxxMD** [comment]
I don't think so -- I used [axios](https://github.com/mzabriskie/axios) with state sources in 0.8 before 0.9 introduced hooks and it worked fine. As you said, as long as it returns a promise I think you'll be fine.

**Comment by dkingman** [comment]
That makes sense. So does the Promise spec dictate the exact names of `catch` and `then`? I don't see anything on `catch` [here](https://promisesaplus.com). Libraries like zepto or jquery have a different api (`fail` vs `catch`).

**Comment by dkingman** [comment]
`axios` actually looks like a better choice than `fetch`. `Fetch`'s author seems pretty adamant about dropping IE support: [https://github.com/github/fetch/issues/96](https://github.com/github/fetch/issues/96).  No support for IE8 planned and IE9 looks like it could be outed.

@jhollingworth any particular reason for choosing `fetch`?

**Comment by bishtawi** [comment]
IE8 and IE9 support is important to me. I tried switching to axios and even though it returns a promise, it doesnt seem to be working with Marty.

**Comment by dkingman** [comment]
I switched to axios and didn't have any issue. The only thing you have to add to any of your `HttpStateSource` classes is:

    request(options) {
        return axios(options);
    }

**Comment by bishtawi** [comment]
Hmm, so I dont think I fully understand how to switch to axios. This is what I have:

````
var AreasHttpAPI = Marty.createStateSource({
  type: 'http',
  id: 'AreasHttpAPI',
  getAreas: function (type) {
    return axios.get('/api/' + type);
    //return this.get('/api/' + type); //Original line
  }
});
````

Am I suppose to switch to axios somewhere else?

**Comment by dkingman** [comment]
That should be fine. Although it would probably be better to do

    var AreasHttpAPI = Marty.createStateSource({
      type: 'http',
      id: 'AreasHttpAPI',
      getAreas: function (
        return this.get('/api/' + type); //Original line
      },
    request: function(options) {
        return axios(options)
    }
    });

Doing it this way will leverage Marty for other types of calls. Like [post, put, delete, etc](http://martyjs.org/api/state-sources/http.html#getUrl).

If that isn't working there is probably something else going on.

**Comment by bishtawi** [comment]
Yeah, its still not working. I can see the request going out but Marty is throwing an error.

**Comment by bishtawi** [comment]
Ah, got it working. I had to update my query to call res.data and not res.body. Also, im doing server side rendering and it looks like the HttpStateSource before hook that marty-express adds doesnt work anymore. Once I worked around that, now it works.

**Comment by jhollingworth** [comment]
> any particular reason for choosing fetch?

Original reason was it was the first decent Ajax lib I'd seen (I was originally using reqwest but was really unhappy with it). I also liked that it was a standard so I could just remove the shim when all browsers support it (unlikely to happen but I can dream :smile:).

Marty doesn't support IE8 so the fact that fetch is dropping it shouldn't be a concern. The fact they're dropping ie9 is concerning though.

I've never seen axios before but I do agree it looks superior. Unfortunately I don't think the benefits of moving to it outweigh the pain in getting people to change their API so I doubt we will make the switch. That said were working on making Marty much more modular on v0.10 so you could customise Marty so it pulls in axios as a dep instead of fetch. 

Looking at promise/a+ spec I don't think catch is part of it so I will update the http state source so it only works with the spec.

**Comment by dkingman** [comment]
Thanks for the response. Agree that API stability is important. It still might be worth deprecating for future removal at some point. That way if fetch does pull the plug on IE9, we aren't scrambling. But as you said, if Marty makes fetch optional then there isn't much benefit to replacing it right now.
