### ISSUE TITLE
this.get() in HTTPStateSource returning undefined instead of promise

### ISSUE THREAD

**Issue by duro** [martyjs/marty#290]
I am using the HTTPStateSource and I have run into a maddening problem. For some reason when I call `this.get(url)` it is returning `undefined` instead of the expected promise.

Here is the file I am working on:

https://github.com/zehnergroup/zg-site-frontend/blob/marty/src/client/app/sources/ServiceCategoryAPI.js

I have debugged the shit out of this, going as deep into the Marty/isomorphic-fetch/fetch internals as I can, and I cannot for the life of me figure out why line 13 of my code returns `undefined`

I am hoping for my own sanity that someone can please have a look and help me out.

**Comment by jhollingworth** [comment]
Thats pretty crazy. ``get`` internally calls ``request`` which only has [one exit which returns the result of ``fetch``](https://github.com/martyjs/marty/blob/master/lib/stateSource/inbuilt/http/index.js#L28). Can you give me any more info? is this on the server? browser (which browser)? Anything else you're doing (e.g. possibly overwriting `fetch`?

**Comment by duro** [comment]
This is happening on the server. I have set breakpoints as deep into the
fetch library as possible and so far all of them get called.

I can't think of anything else that would be overriding fetch.

AD

**Comment by jhollingworth** [comment]
hey, sorry for not getting back sooner. Did you find the issue in the end?

**Comment by duro** [comment]
Yea, it's strange. In Debugger it still returns undefined, but I simply
ignored it and made sure that everything else was working, and managed to
keep moving forward. It's still odd though that it returns undefined and
not a promise object.

**Comment by jhollingworth** [comment]
That is spooky. Well I'm going to close this for now but please re-open if you see any more issues
