### ISSUE TITLE
Properly surface React components rendering exceptions when using Marty container wrappers

### ISSUE THREAD

**Issue by goldensunliu** [martyjs/marty#295]
I have noticed that whenever hasChanged() is fired from a Marty store, rendering exceptions thrown from listening containers' components always are thrown on hasChanged().

Here is an example:
Trying to surface the React component error using marty container, here is a contrived view that will also throw error on render
```javascript
var MyBadUsersView = React.createClass({
  render: function () {
    throw new Error('crap');
  }
});

module.exports = MyBadUsersView
```
this is its container which listen to changes on UserStore
```javascript
var UserStore = require('stores/UserStore');
var MyBadUsersView = require('components/MyBadUsersView');

UsersContainer = Marty.createContainer(MyBadUsersView, 
  {
    listenTo: [UserStore],
    fetch: {
      users: function() {
        UserStore.getAllUsers();
      }
    }
  }
);
```
Here is the store which triggers this.hasChanged() on UserConstans.RECEIVE_USER
```javascript
var UserConstants = require('constants/UserConstants');

var UserStore = Marty.createStore({
  id: 'UserStore',
  
  getInitialState: function() {
    { users: { } }
  },

  handlers: {
    addUser: UserConstans.RECEIVE_USER
  },
  
  getAllUsers: function() {
    this.fetch({
      id: 'getAllUsers',
      locally:  function() {
        return this.state.users
      }
    })
  },

  addUser:  function(user) {
    this.state.users[user.id] = user;
    // This is where the rendering exception is thrown
    try {
      this.hasChanged();
    } catch (error) {
      // Error('crap') is caught here
      console.log(error);
    }
  }
});
```
As you can use the rendering exception thrown in the component surfaces when this.hasChanged() is called in UserStore. 

My question is: Is there anyways for React components within a Marty Container to surface their rendering exceptions to top of the application?

**Comment by taion** [comment]
Resolved by #320.
