### ISSUE TITLE
Nested Routes and Stores

### ISSUE THREAD

**Issue by thecaddy** [martyjs/marty#296]
First I wanted to say thank you for the great library.

I have an application that has Store A and Store B under respective routes A and B.  The fetch of B is dependent on the id's returned by the fetch of A.  Is there any way, even a hackish way I could get server side rendering to generate the markup for this case.

I've tried a few things and it looks like it does call for the data when marty calls 'React.renderToString' but it doesn't wait for the fetch to return.

```
 <Route name="A" path="/a"/>
    <Route name="B" path="b" handler={ require('./BComponent') } >

    <DefaultRoute handler={ require('./AComponent') } />
</Route>

```

```
export default Marty.createContainer(BComponent, {
  listenTo: BStore,
  fetch: {
    b() {
      return BStore.for(this).getBs(this.props.a.ids);
    }
  }
});
```

**Comment by edvinerikson** [comment]
Hi.
Have you tried to call the [`waitFor`](http://martyjs.org/api/stores/#waitFor) method? 
I'm not sure it will work but it's worth a try. :smile:

**Comment by jhollingworth** [comment]
Sorry for delay in replying to this. `dependsOn` might be what you want

```js
class SomeStore extends Marty.Store {
  getFoo(barId, fooId) {
    return this.fetch({
      id: barId,
      dependsOn: this.getBar(barId),
      locally() {
        return this.bars[barId].foos[fooId]
      }
    })
  },
  getBar(barId) {
    return this.fetch({
      id: barId,
      locally() {
        return this.bars[barId];
      },
      remotely() {
        return BarAPI.getBar(barId)
      }
    })
  }
}
```

**Comment by jhollingworth** [comment]
I'm gonna close this now, please re-open if this doesn't solve your problem

**Comment by thecaddy** [comment]
We tried both waitfor and dependsOn, what ends up happening on the server is it returns the request but you can see the server still processing the nested request, it makes the necessary async calls but the response/html has already been returned by marty.

**Comment by ntkoso** [comment]
@thecaddy Try 0.9.15 version. It could be the same issue as #314 (nested fetches).

**Comment by thecaddy** [comment]
Ah ok great.  We'll take a look.  We coded a workaround for now but we'll dedicate some time to take a look.
