### ISSUE TITLE
HttpStateSource throws error on json response with empty body

### ISSUE THREAD

**Issue by hansihe** [martyjs/marty#297]
When the remote end returns a response with a json content type, and with an empty body, an error gets thrown from the `parseJSON` hook. The error originates from the browsers `JSON.parse` function, which throws an error when called with an empty string.

The easiest way for me to deal with this would be to add a check to the `isJson` function in `parseJSON.js`. However, since an empty string is not valid json, I am not sure if this would be the right way.

I would argue that a server returning an empty string with a json content type is a scenario which is not necessarily all that uncommon, and should be dealt with in some way in the library.

If you agree it would be right to have such a check, I would be happy to submit a pull request implementing it.

**Comment by jhollingworth** [comment]
Hey, sorry for the delay in replying.

Change makes sense and happy for you to send a PR :+1: 

Should warn you though that we're going to be [deprecating  parseJSON in v0.10](https://github.com/martyjs/marty/issues/293#issuecomment-100446382) as its causing lots of issues

**Comment by hansihe** [comment]
Alright, since parseJSON is being deprecated soon, I don't think there is any purpose to making changes.
