### ISSUE TITLE
Container fetch design doesn't allow for partial rendering

### ISSUE THREAD

**Issue by pbomb** [martyjs/marty#300]
I'm not seeing how I can render a container's inner component with the fetched results that have finished, if others are still pending. In this state, the container only sees a pending fetch result, with no way to get at the individual fetches.

Is there something I can do to workaround this? Am I missing something? I haven't yet figured out how to do this.

Thanks

**Comment by jhollingworth** [comment]
right now its all or nothing but I can see that would be useful.

How about we pass in all the finished fetch results into the `pending` handler?

```js
Marty.createContainer(Component, {
  fetch() {
    return {
      foo: FooStore.getFoo(),
      bar: BarStore.getBar()
    }
  },
  pending(results) {
    _.defaults(results, {
      foo: DEFAULT_FOO,
      bar: DEFAULT_BAR
    });

    return <Component {...results} />
  }
});
```

**Comment by chrisbarmonde** [comment]
Yeah, I've done something similar where I just make pending something like:
```javascript
pending: function() {
    var defaults = {whatever: 'whatever'};
    return this.done(defaults);
}

**Comment by jhollingworth** [comment]
I've just published v0.9.12 which has the above solution in there

**Comment by pbomb** [comment]
:+1: Thanks, James!

**Comment by jhollingworth** [comment]
Gonna close this now
