### ISSUE TITLE
Should stores work directly with WebAPI?

### ISSUE THREAD

**Issue by rymohr** [martyjs/marty#31]
> Stores are responsible for fetching their own data so getInitialState is a good place to make any API calls.

Came across this in the docs and I'm wondering if it would be better practice to call `UsersAPI.getAll` indirectly through an action creator instead.

``` js
var UsersStore = Marty.createStore({
  getInitialState: function () {
    UsersAPI.getAll();
    return [];
  }
});

// vs

var UsersStore = Marty.createStore({
  getInitialState: function () {
    UserActionCreators.getAll();
    return [];
  }
});
```

![image](https://cloud.githubusercontent.com/assets/730211/5176307/0342f9f8-73eb-11e4-99b1-f410080d6530.png)

The more I think about it the less I think it's the store's responsibility at all.

**Comment by hugobessaa** [comment]
Just to clarify things up: if I had a UsersStore, and want to implement a search form for users, that search form should call `UsersStore.getByQuery('query')`?

It is pretty blurry how Flux components should handle fetching.

**Comment by jhollingworth** [comment]
Hey, yes thats right. The store should internally check if it has that result cached and if not call the state source (See [fetching data](http://martyjs.org/guides/stores/fetching-data.html)

**Comment by hugobessaa** [comment]
Thanks! This issue helped me a lot.
