### ISSUE TITLE
Use of container components in loops, adjancy

### ISSUE THREAD

**Issue by Rodeoclash** [martyjs/marty#316]
I'm going to try to put together a gist for this but I wanted to check: Is their anything not listed in the documentation about using container components in arrays with a ```key``` property on them?

I'm see some strange behaviour and warnings, in particular React suggesting that I use the ```React.addons.createFragment``` method (which I've experimented with).

I'll try to replicate in a gist in about 18 hours unless theirs something obvious I've missed in the docs.

**Comment by taion** [comment]
I'm not aware of anything, but I don't recall specifically whether I've tried to use this pattern.

**Comment by Rodeoclash** [comment]
Ok, I'll close this and create a new ticket if I can replicate in a jsfiddle.
