### ISSUE TITLE
Bug: Adding hook with no 'id' throws

### ISSUE THREAD

**Issue by idolize** [martyjs/marty#328]
Example:
```js
var myHook = {
  before(req) {
    console.log('running (before) of hook!');
  }
};

console.log('adding Marty hook');
Marty.HttpStateSource.addHook(myHook);
console.log('success!');
```

Results in the following:
```
adding Marty hook
(Exception) failed to post message Object {id: "c60c89846534da2d", action: Object, stores: Object} TypeError: Converting circular structure to JSON
```

But, changing the hook to:
```js
var myHook = {
  id: 'MyHook',
  before(req) {
    console.log('running (before) of hook!');
  }
};
```

Works as expected:
```
adding Marty hook
success!
```

**Comment by jhollingworth** [comment]
Odd, its [expected behaviour to throw an error if the hook doesn't have an Id](https://github.com/martyjs/marty-lib/blob/master/src/http-state-source/http.js#L54-L56). Not sure why you're getting a different error though

**Comment by taion** [comment]
I see the "hook must have an id" error when I run your code sample against the latest Marty. Maybe something else in your environment?

**Comment by taion** [comment]
Closing for now, let me know if this pops up again.

**Comment by idolize** [comment]
Thanks guys. I think the cryptic exception was some weirdness related to the Marty DevTools extension that was hiding the real exception message.
