### ISSUE TITLE
Dispatching _FAILED actions from source promises

### ISSUE THREAD

**Issue by idolize** [martyjs/marty#329]
I see in the v0.10 docs it [recommends the following pattern](http://martyjs.org/guides/fetching-state/index.html):

```js
class UserAPI extends Marty.HttpStateSource {
  getUser(userId) {
    var url = 'http://jsonplaceholder.typicode.com/users/' + userId;

    return this.get(url).then(function (res) {
      if (res.ok) {
        return res;
      }

      throw res;
    });
  }
}

class UserQueries extends Marty.Queries {
  getUser(userId) {
    this.dispatch(UserConstants.RECEIVE_USER_STARTING, userId);

    return this.app.userAPI.getUser(userId)
      .then(res => this.dispatch(UserConstants.RECEIVE_USER, userId, res.body)_
      .catch(err => this.dispatch(UserConstants.RECEIVE_USER_FAILED, userId, err);
  }
}
```

However, in my testing, I noticed I was getting both `UserConstants.RECEIVE_USER` and `UserConstants.RECEIVE_USER_FAILED` dispatched in the failure case (possibly because of the `throw` not happening until the `this.get(url).then()` callback?).

I assume this is not the expected behavior, because I was under the impression that only one of the two actions (`RECEIVE_USER` or `RECEIVE_USER_FAILED`) should be dispatched.

I worked around it with the following function, but it seems a bit unnecessary:

```js
export function wrapPromise(promise) {
  return new Promise((resolve, reject) => {
    promise.then(res => {
      throwIfError(res);
      return resolve(res);
    }).catch(err => {
      return reject(err);
    });
  });
}
```

**Comment by taion** [comment]
Is it possible that the

```js
this.dispatch(UserConstants.RECEIVE_USER, userId, res.body)
```

call is throwing? It seems like that could potentially lead to both actions getting dispatched.

I think in general it'd be safer to write those constructs as `.catch(...).then(...)`.

**Comment by idolize** [comment]
Nevermind, this seems to have been an issue with a previous version of Marty (pre-0.10) and after further testing does not seem to repro.

Thanks all!
