### ISSUE TITLE
Expose static methods from component classes wrapped in containers

### ISSUE THREAD

**Issue by lemonCMS** [martyjs/marty#338]
I've got a component which uses the willTransitionTo static method from react-router. Wrapping this component in a Marty container seems to stop this from being called. I've had a look through the Marty source and it looks like, in the process of cloning the component to return the new one that listens to the stores etc, willTransitionTo is being stripped out so doesn't actually exist in the new component returned from createContainer. Is this right or is something else happening?

Original issue posted on: https://gitter.im/martyjs/marty - June 8 2015

**Comment by jaraquistain** [comment]
@lemonCMS I've ran into the exact same issue and a bit of googling around has told me that with the eventual release of react-router 1.0 this problem will be addressed. Would be great if it already worked as is, though, since there's no telling when react-router 1.0 will be released

**Comment by mwillmott** [comment]
Original poster here... you beat me to opening an issue @lemonCMS.

@jaraquistain can you point to where you found this out? As far as i'm aware this is entirely a problem with how the createContainer method clones (or doesn't clone) static methods from the original component.

**Comment by taion** [comment]
Let's just handle a `statics` key on the `options` object passed into `createContainer`, analogous to #224.

**Comment by taion** [comment]
And maybe add an `@expose` decorator to make this easier. As you can tell, the HOC abstraction is a little leaky, but I think these bits are manageable.

**Comment by jaraquistain** [comment]
@mwillmott [here](https://github.com/rackt/react-router/pull/1158)'s what I was referring to (Specifically the Transition Hooks section). As far as I understand it the static transition hooks are being discarded in favor of explicit listeners declared on a component. There is a decent chance that I'm misunderstanding it, though.

Like I said, though, its only in alpha right now so it'd be great to get something going like what @taion was suggesting.

**Comment by taion** [comment]
I think longer term, we'll want to add e.g. an `@Marty.exposed` or `@Marty.containerExposed` decorator to make it easy to just forward both static and non-static methods (when using ES7), but martyjs/marty-lib#20 should get you enough to resolve this issue.

**Comment by jhollingworth** [comment]
Released in marty v0.10.4

**Comment by taion** [comment]
Oops. Turns out this was totally possible in v0.10.3 because of createClass's implementation, so https://github.com/taion/marty-lib/commit/4d4281e4ad2770548844e46074d3b2c81b66ec5a was completely unnecessary.

Just pass in `statics` as an option to `createContainer`. That said, because it's static, you won't be able to access the app from there, but at least you can call the static methods on the wrapped component.

**Comment by lemonCMS** [comment]
Can you perhaps give an code example on how to use the willTransitionTo in the createContainer? I could not get it to work.

**Comment by mwillmott** [comment]
I'm with you @lemonCMS, i still can't get willTransitionTo to work.

**Comment by taion** [comment]
See: http://martyjs.org/api/containers/index.html#other-options

This attaches statics to the container. Note that because it's a static, you won't be able to access the app instance, per #322.

**Comment by mwillmott** [comment]
Ah! Completely missed that. Works fine now.

**Comment by lemonCMS** [comment]
aha! That works! thx
