### ISSUE TITLE
Make guide in docs more terse

### ISSUE THREAD

**Issue by taion** [martyjs/marty#339]
Compare to http://martyjs.org/v/0.8.15/guides/getting-started/ to http://martyjs.org/v/0.10.3/guides/getting-started/ - there's almost twice as many sections in the guide now, even though there aren't that many new concepts.

We should combine and shorten some of those sections and move more of the documentation into the API section.

**Comment by taion** [comment]
I would structure this as:

1. Guide - just shows minimal set of things needed to get a modern app going: constants, HTTP state source, action creators/queries, store, application, application container, container (in ES5 and ES6 styles for all of these)
2. Reference - extended docs for the other parts, including deprecated features, mixins, and other state sources, as well as API docs

**Comment by zrosenbauer** [comment]
+1

**Comment by taion** [comment]
No longer relevant.
