### ISSUE TITLE
Document Store#clear

### ISSUE THREAD

**Issue by songawee** [martyjs/marty#342]
I see in store.js that stores come with a clear() function - https://github.com/martyjs/marty-lib/blob/master/src/store/store.js#L91, but this method isn't mentioned in the docs. We have found ourselves writing our own clearState method, but were wondering if this method would be ok to use? If it's just missing from the docs, I can submit a pr as well.

**Comment by taion** [comment]
Funny enough, it looks like it _should_ be documented, but isn't: http://martyjs.org/api/application/index.html#clearState
