### ISSUE TITLE
How to distinguish code running on server or on browser? Do I even have to?

### ISSUE THREAD

**Issue by SudoPlz** [martyjs/marty#347]
Hello, I love Marty, but since this is my first time creating an isomorphic app, I'm really making baby steps all the way.

**1)** I'm trying to figure if I the same code will run with no problems in both the mobile server and the browser.
For instance I've got this `header.js` file:
```javascript
    'use strict';
    var React = require('react');
    var ReactPropTypes = React.PropTypes;
    var Marty = require('marty');
    var SessionStore = require('../stores/sessionStore');
  
        var Header = React.createClass({
    
        displayName: 'Header Component',
    
        propTypes: {
            //email: ReactPropTypes.string,
            isLoggedIn: ReactPropTypes.bool
        },
    
        getInitialState: function() {
            return {}; // email: null, isLoggedIn:false
        },

        render: function() {
            return (
                <div >
                  <h1 >This will someday be a nav bar! Logged in: {this.props.isLoggedIn?'yes':'no'}</h1>
                </div>
            );
        }
    });
    
    
    
    
    module.exports = Marty.createContainer(Header, {
        listenTo: 'SessionStore',
        fetch: {
            isLoggedIn() {
                //this.context.marty.resolve(SessionStore)
                return  SessionStore.for(this).isLoggedIn();
            }
    
        }
    });
```
    
**2)** I noticed on some examples use `this.app` so I wonder if instead of 
`return  SessionStore.for(this).isLoggedIn();` I should write `return this.app.SessionStore.for(this).isLoggedIn();` or something...
**3)** Also does` hydration rehydration` work out of the box if I implement the `hydrate, dehydrate` methods on each store?

Thank you, please shed some light into my confused universe of Marty!

**Comment by engineersamuel** [comment]
I was going to open a new issue but this is close enough.  There is ambiguity for how one is suppose to handle the rehydration in the the client side.

The app I am working on, https://github.com/redhataccess/jvmpeg, is correctly loading the initial load isomorphically and I've debugged the marty-express code to verify the locals: state does contain the serialized state.  However once the client side takes control I see a 'loading...' where my Store reloads the data that is already there.  This shouldn't happen.  

The docs indicate that one should hydrate/dehydrate in the Store, however, it also says that if the function isn't implemented the default is used.  If I look at https://github.com/martyjs/marty-lib/blob/master/src/store/store.js I see no default rehydrate or dehydrate implementation or hooks as to such methods are called.  I only see rehydrate mentioned in the application.js:

https://github.com/martyjs/marty-lib/blob/e2640804254e796dd9ce03332e05239a2881c24d/src/application/application.js#L181

I guess a next step could be to debug that application.js to see if it is actually rehydrating the store in question, some clarification would be very helpful as well here.

**Comment by taion** [comment]
It works like this - https://github.com/martyjs/marty-lib/blob/v0.10.6/src/application/application.js#L196-L210, i.e. if the store doesn't explicitly implement `#rehydrate()`, it just uses `#replaceState()`.

**Comment by engineersamuel** [comment]
Actually I do believe there is something missing.

See https://github.com/martyjs/marty-chat-example-es6/blob/master/app%2Fserver%2Fviews%2Findex.ejs

There is no <%- state %> anywhere for Marty to render and later read.  I would expect there to be considering part of the ejs rendering in marty-express sets state as a local:

```javascript
 function onRendered(renderResult) {
        var locals = options.locals || {};

        locals[options.body || 'body'] = renderResult.htmlBody.trim();
        locals[options.state || 'state'] = renderResult.htmlState.trim();

        res.render(options.view || 'index', locals);

        if (_.isFunction(options.rendered)) {
          options.rendered(_.extend({
            req: req
          }, renderResult));
        }
      }
```

Body is used in the index.ejs in the chat example but state is not.  When debugging through the application.js state is undefined which means it's never read from the html from node, which makes sense.

**Comment by engineersamuel** [comment]
Yeah that was it, I created a pull request for the chat example, drove me insane, but I'm glad I found it: https://github.com/martyjs/marty-chat-example-es6/pull/4

**Comment by SudoPlz** [comment]
Shit I knew that, I wasn't aware that was what you needed. I found that code in chat example https://github.com/martyjs/marty-chat-example/blob/master/app/index.js.

**Comment by taion** [comment]
Sounds like this is resolved.

**Comment by SudoPlz** [comment]
In case someone is looking for the answer to this question, its : 
```javascript
if(Marty.isBrowser){
    //Code that runs only in browser side
}else{
    //Code that runs only in server side
}
