### ISSUE TITLE
Throttle Fetches

### ISSUE THREAD

**Issue by chapinkapa** [martyjs/marty#348]
Can we look at adding throttle support to fetches? It could look like this:

    return this.fetch({
      throttle: 500, //milliseconds
      id: 'profile',
      locally: function() {
        if (this.hasAlreadyFetched('profile')) {
          return this.state;
        }
      },
      remotely: function() {
        return profileQueries.getProfile();
      }
    });

**Comment by taion** [comment]
How specifically would this work?

**Comment by chapinkapa** [comment]
It will only allow 1 remote call per specified time.

**Comment by taion** [comment]
I don't really understand you example, though - `Store#fetch` collapses pending fetches. Unless you manually clear the store, I don't see how the `remotely` on the above fetch would be called more than once, ever.

**Comment by chapinkapa** [comment]
I may be doing it wrong. Basically, I have 2 separate components which are both using the same store.

These two components can be initialized at the same time (one is for the header, one is for one of my routes).

When they are both initialized, they have the store try to fetch, since profile has not yet been fetched yet, they both are causing a network request. So, I am getting 2 request when I would prefer just 1 request.

Does this make more sense?

**Comment by taion** [comment]
That shouldn't happen this way. Per http://martyjs.org/api/stores/index.html#fetch-options:

>Only one request for a given Id can be in progress at any time. If another request is in progress then a pending fetch result is returned

If you're seeing different behavior, then we have a bug here.

**Comment by chapinkapa** [comment]
Ah. I am still on 0.9. We are planning on upgrading next week to 0.10. I am guessing that will fix this.

**Comment by oliverwoodings** [comment]
It should work in 0.9 as well

**Comment by chapinkapa** [comment]
My Profile Store:

      getProfile() {
        return this.fetch({
          id: 'profile',
          locally: function() {
            if (this.hasAlreadyFetched('profile')) {
              return this.state;
            }
          },
          remotely: function() {
            return profileQueries.getProfile();
          }
        });
      }
      
My Nav Component:

    componentWillMount() {
        ProfileStore.getProfile();
    }
    
My Profile Component:

    var ProfileContainer = Marty.createContainer(Company, {
        listenTo: [
            ProfileStore
        ],
        
        fetch() {
            return {profile: ProfileStore.getProfile();
        },
        
        failed(errors) {
            return false;
        },
        
        pending() {
            return false
        }
    });

My Network request showing 2 request going out:

![screen shot 2015-06-26 at 12 15 10 pm](https://cloud.githubusercontent.com/assets/4140149/8383120/61eae712-1bfd-11e5-81da-ab555ceeec68.png)

**Comment by oliverwoodings** [comment]
Can you try changing the 'this.hasAlreadyFetched' line to instead check to
see if this.state has your profiles in? Wondering if it is a bug with
hasAlreadyFetched

**Comment by taion** [comment]
@oliverwoodings 

You're right - looking at the code, the dispatch to populate the store gets processed before we set the fetch history entry: https://github.com/martyjs/marty-lib/blob/e2640804254e796dd9ce03332e05239a2881c24d/src/store/storeFetch.js#L79-L86

@chapinkapa 

You should use the pattern where you set the value onto e.g. `state.data` instead of the `state` object itself. Then in `locally()`, just return `state.data`. Don't explicitly check for `hasAlreadyFetched` in `locally`.

**Comment by chapinkapa** [comment]
@taion @oliverwoodings thank you guys.

Returning 'state.data' works.

**Comment by taion** [comment]
Closing this issue then. Let me know if there are other problems. We should document this better.

**Comment by Rodeoclash** [comment]
I just ran into this one as well, took me a while to debug what was going on. A warning about using ```hasAlreadyFetched``` would be great!
