### ISSUE TITLE
How to fetch data from the store into my container?

### ISSUE THREAD

**Issue by SudoPlz** [martyjs/marty#352]
I don't understand how the container works.. All I'm trying to do is fetch some data from my store (which fetches its data from a rest call).

Watching this store in your example: 

        //https://github.com/martyjs/marty-chat-example/blob/master/app/stores/roomsStore.js
	getAll: function () {
	    return this.fetch({
	      id: 'all-rooms',
	      locally: function () {
	       //bla bla
	      },
	      remotely: function () {
	        //bla bla
	      }
	    });
	},	

makes me wonder why do we need 2 functions, 1 `remotely` and 1 `locally`? Do I need to implement both?

This is my store called SessionStore.

        var {API_ENDPOINTS, SESSION_CONSTANTS} = require('../constants/Constants');
        var Marty = require('marty');
        var rest = require('superagent');

	var SessionStore = Marty.createStore({
	    id: 'SessionStore',
	    handlers: {
	        login: SESSION_CONSTANTS.LOGIN_REQUEST
	    },
	    getInitialState: function () {
	        return {currentUser:''};
	    },
	    isLoggedIn: function () {
	        return (this.state.currentUser!='');
	    },
	    login: function(username, password) {

	        request.post(API_ENDPOINTS.LOGIN)
	            .send({ identifier: username, password: password })
	            .set('Accept', 'application/json')
	            .end(function(error, res){
	                //console.log("Error: "+error+ "responce: "+JSON.stringify(res));
	                if(error) return false; //do something in case of an error?
	                if (res) {
	                    var responseParsed = res.body;
	                    if(responseParsed.success){
	                    //ALL GOOD!
    	                        return true;                      //Is this a correct way to return data to my container?
    	                    }else{
     	                        return false;                     //Is this a correct way to return data to my container?
    	                    }
	                }
	            });
	    },
	});

Is my way of returning results correct? Also I noticed I don't have to use `superagent` since you provide rest calls in marty through state sources, but can a `store` also be a state store in order to call a method like `this.post()` ?

Thank you...

Bah, thats confusing...

**Comment by codyhatch** [comment]
For the first question, let's suppose you have a container like so:

```
export default Marty.createContainer(MyComponent, {
    listenTo: ['myExampleStore'],
    fetch: {
        values() {
            return this.app.myExampleStore.getValues();
        }
    }
}
```

What this is saying is that MyComponent would like to have whatever myExampleStore returns from `getValues` available as `this.props.values`.  Then on your store, you want something like:

```
export default class MyExampleStore extends Marty.Store {
    getValues() {
        return this.fetch({
            id: 'values',
            locally: () => this.state.values,
            remotely: () => this.app.myExampleQueries.getValues()
        });
    }
}
```

What happens is that every time your component is rendered, it'll hit `getValues()` on the store.  Each time, fetch will hit the `locally` handler first, to see if the store already contains that data.  If it doesn't (which is detected by `locally` returning undefined), it will then hit the `remotely` handler which is meant to trigger a query to, eventually, hit a state source.  When remotely finishes, it will re-run `locally`, which should contain the value (if `remotely` worked), or will return undefined (if your state source couldn't get the value either).

So yes, you normally need to implement both, but `locally` just returns data from the store's state, and `remotely` just triggers a query.  Neither one is meant to be a big function.

Finally, not entirely sure what you're trying to do with the login method, but that's not going to do anything useful.  Your login request should probably fire some sort of LOGIN_SUCCESSFUL action on success, which your SessionStore listens to with some sort of `receiveSession` handler, which updates the store's state.  Your container should get the state via some sort of `getSession` method.

**Comment by SudoPlz** [comment]
Thank you... 
You totally and absolutely filled the gaps for me.. 
I plan to fire a Login_successfull action indeed.
If only the above explanation could be copied and pasted into the docs. Did I somehow miss it? You really helped me understand how it works, I really really appreciate it.
AGAIN Thank you.!!

Now could you or someone else be kind enough to answer a few more questions:

1) How is a query identical to an action creator when in [your Query docs example](http://martyjs.org/guides/queries/index.html) you clearly run code and do stuff. (more than what an action creator would do - which is to dispatch an event).

1) Is there a reason I should prefer to use [the built in (Marty) session storage](http://martyjs.org/api/state-sources/session-storage.html) for keeping data like the user email, token etc, or is it ok to just keep those in my `SessionStore` as I'm doing now.

2) Can a `store` be an http [state source](http://martyjs.org/api/state-sources/http.html) as well? (So that I get rid of external restful libraries like superagent to access my backend api)

**Comment by danillo2k** [comment]
1) Actually it is exactly as said in the link you provided -> you use queries for reads and action creators for writes. they both eventually dispatch an event, so for example: if u wish to query for user(id) you would use queries, but if u want to update user(id) you would use the action creator. 

so in the example above:

    export default class MyExampleStore extends Marty.Store {
        getUser(id) {
            return this.fetch({
                id: id,
                locally: () => this.state.user[id],
                remotely: () => this.app.userQueries.getUser(id)
            });
        }
    }

getUser = your query 

    class UserQueries extends Marty.Queries {
      getUser(id) {
        this.dispatch(UserConstants.RECEIVE_USER_STARTING, id);
        this.app.userAPI.getUser(id).then(
          res => {
            if (res.status === 200) {
              this.dispatch(UserConstants.RECEIVE_USER, res.body, id);
            } else {
              this.dispatch(UserConstants.RECEIVE_USER_FAILED, id);
            }
          },
          err => this.dispatch(UserConstants.RECEIVE_USER_FAILED, id, err)
        );
      }
    }

and in your store:

    constructor(options) {
      super(options);
      this.state = {};
      this.handlers = {
        login: UserConstants.LOGIN,
        getUserStarting: UserConstants.RECEIVE_USER_STARTING,
        getUserSuccess: UserConstants.RECEIVE_USER_DONE,
        getUserFailed: UserConstants.RECEIVE_USER_FAILED,
        updateUserStarting: UserConstants.UPDATE_USER_STARTING,
        updateUserSucces:UserConstants.UPDATE_USER_DONE
        updateUserFailed: UserConstants.UPDATE_USER_FAILED
      }
    }

    getUserStarting() {
    //whatever
    }

    getUserSuccess(user, id) {
     this.state.user[id] = user;
    }

    getUserFailed() {
    //whatever
    }


----
update user:

    class UserActionCreator extends Marty.ActionCreators {
      updateUser(id) {
        this.dispatch(UserConstants.UPDATE_USER_STARTING, id);

        this.app.userAPI.updateUser(id).then(res => {
          this.dispatch(UserConstants.UPDATE_USER_DONE, user.cid, res.body);
        }).catch(err => {
          this.dispatch(UserConstants.UPDATE_USER_FAILED, id, err.body);
        });
      }
    }



2. I don't know how u are doing it now, but for simple get and set, what marty provided should be enough.
3. "Can a store be an http state source as well? (So that I get rid of external restful libraries like superagent to access my backend api)"

I don't understand the question, your stores is where the state lives, the sources (if remotely) u query, so your store should not be a http state source, i don't see how it could. your queries, and actions are the way to trigger communication with your sources. Your store is where the state is set, which will update the components that are making use of it. But if u are using external restfull libraries, u shouldnt have to, depending on the complexity of what u are doing, but with marty http state source u can do CRUD.

**Comment by SudoPlz** [comment]
1. Ok my question was a bit weird, but nevermind, I'll be using marty sessions anyway.

2. I take it that a Marty store, can not be an http state source itself. By that I mean, I can not run get,post requests from within a marty store, I have to create another class, a state source class to do so because a store cannot also be a state source.
I've decided the answers for myself on the above 2 questions.



but my main question was the 3rd:
3) Why do you run code and do stuff in `action creators` and `queries`. By that I mean, why have `CRUD` calls within `action creators` and `queries`... 

I thought the sole purpose of an `action creator` or a `query` (in Flux) was to "**JUST  dispatch an event**, in order for an action to **begin**" rather than "just *do an action* and *dispatch its result*"? I see you do follow second

**Comment by taion** [comment]
Ignoring the query/action creator distinction for now, which is more for organization or whatever, it is in fact correct to initiate REST calls from the action creators - see e.g. https://github.com/facebook/flux/blob/master/examples/flux-chat/js/actions/ChatMessageActionCreators.js. As for why action creators... well, where else would you put them?

**Comment by SudoPlz** [comment]
Ok, thanks @taion, I didn't know that. I thought perhaps you could put that logic inside store methods.
