### ISSUE TITLE
Return error in locally

### ISSUE THREAD

**Issue by jaulz** [martyjs/marty#368]
Is it possible to return a custom error in locally? Thanks :)

**Comment by taion** [comment]
You can return whatever you want in `locally`.

**Comment by jaulz** [comment]
But this would not trigger the ```failed``` callback. Basically my `remotely` returns a promise which is rejected with the actual error object but as my `locally` is called afterwards the error is forgotten. Any idea how to reflect this?

**Comment by taion** [comment]
Your `locally` needs to not return a valid value for the failure handling to work. Alternatively, you can return a sentinel value in `locally` that your component can render appropriately into an error.

**Comment by jaulz** [comment]
I don't want to handle the error in the component itself but instead it should be automatically handled in the container. This is nothing which one can do today if I understand the code correctly. Should this be a feature request?

**Comment by taion** [comment]
Just `throw` in your `locally`.
