### ISSUE TITLE
not properly escaping "</script>" in app state dehydration

### ISSUE THREAD

**Issue by jaraquistain** [martyjs/marty#370]
In our app, we cannot save user generated strings with html-escaped entites because the APIs are being consumed by non web applications and I can't dictate that all consumers of the API must parse the data as HTML.

As a result, when I set my name to `"</script>"` in our app and refresh the page, a javascript error results because the application.htmlState that is generated looks like this (the relevant part is the `"name": "</script>"` inside the userStore):

```html
<script id="__marty-state">(window.__marty||(window.__marty={})).stores={"userStore": {"fetchHistory": {"user_6": true},"state": {"current": null,"items": {"6": {"id": 6,"url": "/users/6","name": "</script>","email": "***","phone": "***","email_verified": false,"phone_verified": false,"networks": []}}}}}</script>
```

Of course when inserting this state into the template (handlebars in my case) I cannot escape it because it is javascript that needs to run (`{{{state}}}` instead of `{{state}}`) and as a result the `"name": "</script>"` part closes the opening script tag and errors out on everything else that comes after it. 

One potential solution I could implement on my side would be to html escape all externally fetched data before putting it into the stores, but I really feel like this is a case that should also be handled by marty itself as there may be other vulnerabilities caused by this same exact thing that I don't even realize.

EDIT: I actually just realized I can't santize it before putting it into the store because react also sanitizes everything so any HTML entity would get double-escaped

@taion let me know if you'd like any more context or information.

**Comment by taion** [comment]
Nope, I've got this. Working on a patch.

@jhollingworth We'll definitely want to cut a new release for this. It's a pretty severe bug.

**Comment by taion** [comment]
As in this is a glaring XSS vulnerability - need to patch ASAP.
