### ISSUE TITLE
Consider reversing order in this.handlers

### ISSUE THREAD

**Issue by DennisFrostlander** [martyjs/marty#374]
Here is an annoying suggestion ;) Could you consider reversing the order of data we need pass to this.handlers in the store?
So instead of this.handlers = {methodName: actionName}, you would write this.handlers = {actionName: this.methodName}. I know it's painful to change this, so maybe a new method could be introduced (e.g. like bindActions in fluxxor).

There are couple of reasons:
- No need to have method name string matching (e.g. easier refactoring)
- IDE will stop complaining about all these handler methods not being used (because there would be an explicit this.reference in the code)
- And to me personally it's somehow easier to read the flow in this way - when action X happens, run method Y. 

I know you will then lose the possibility to bind the same handler to multiple events using an array as a value, but I would rather duplicate the binding for each action.

**Comment by taion** [comment]
It's recommended to use the `@handles` decorator anyway if you're using at least Babel stage 1.

**Comment by DennisFrostlander** [comment]
@taion Thanks for the cool tip, did not know about this decorator.

**Comment by taion** [comment]
Well, it's not documented... yet.

Does that work for your use case?

**Comment by DennisFrostlander** [comment]
Certainly! Ditching now all my handlers in favor of the new decorator. So I guess my initial becomes irrelevant now.
