### ISSUE TITLE
Support React 0.14.0

### ISSUE THREAD

**Issue by chapinkapa** [martyjs/marty#379]
Can we upgrade marty to support react 0.14.0?

On another note, if we want to keep using marty, do you suggest we just fork it and rebrand it? Are you open to having someone else maintain it?

**Comment by taion** [comment]
I'll bump the dependency. I still have some legacy projects that I haven't cut over from Marty yet, and I guess others might too.

That said, I'd strongly recommend migrating to a different Flux framework, or looking into Relay going forward.

**Comment by taion** [comment]
That said, if you're interested in maintaining, I don't see anything wrong with adding you or others as a collaborator, though that'd be up to @jhollingworth. I'll continue to review and merge (eventually) PRs for the time being, at least until we're off Marty on our side.

**Comment by jhollingworth** [comment]
Happy to add maintainers but I'm against forks. Marty is its own organisation so that its decoupled from any specific maintainer

**Comment by jhollingworth** [comment]
It would be good to see some PRs before I add anyone as a maintainer though

**Comment by taion** [comment]
Closed by #380.

**Comment by taion** [comment]
I'm deliberately not updating the docs, BTW. There's no point - this is a pure band-aid fix.
