### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by sdtsui** [martyjs/marty#383]
https://github.com/martyjs/marty/commit/ea2ffbd28e6e4a16d4fe7a24f43e9372374959de

This fix was merged before. Live site [here](http://martyjs.org/guides/fetching-state/index.html) doesn't currently reflect the change.

**Comment by taion** [comment]
This is pretty low-priority to me – it doesn't really make sense to use this library any more; switch to Alt or Redux.

**Comment by sdtsui** [comment]
Got it. Thank you!
